#!/usr/bin/env python3
"""Generate platform-specific Go icon data without 2goarray."""

from __future__ import annotations

import argparse
import binascii
import struct
import tempfile
import zlib
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = ROOT / "assets"
ICON_DIR = ROOT / "internal" / "icon"


def write_go_array(output: Path, build_tag: str, data: bytes, source: str) -> None:
    lines = [
        f"//go:build {build_tag}",
        "",
        f"// Code generated by generate_icons.py from {source}; DO NOT EDIT.",
        "",
        "package icon",
        "",
        "var Data []byte = []byte{",
    ]
    for idx in range(0, len(data), 12):
        lines.append("\t" + "".join(f"0x{byte:02x}, " for byte in data[idx : idx + 12]))
    lines.append("}")
    lines.append("")
    output.write_text("\n".join(lines))


def png_chunk(chunk_type: bytes, data: bytes) -> bytes:
    checksum = binascii.crc32(chunk_type + data) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + chunk_type + data + struct.pack(">I", checksum)


def paeth(left: int, up: int, up_left: int) -> int:
    estimate = left + up - up_left
    dist_left = abs(estimate - left)
    dist_up = abs(estimate - up)
    dist_up_left = abs(estimate - up_left)
    if dist_left <= dist_up and dist_left <= dist_up_left:
        return left
    if dist_up <= dist_up_left:
        return up
    return up_left


def read_rgba_png(path: Path) -> tuple[int, int, int, bytearray]:
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError(f"{path} is not a PNG file")

    pos = 8
    ihdr = None
    idat = bytearray()
    while pos < len(data):
        length = struct.unpack(">I", data[pos : pos + 4])[0]
        chunk_type = data[pos + 4 : pos + 8]
        chunk_data = data[pos + 8 : pos + 8 + length]
        pos += 12 + length
        if chunk_type == b"IHDR":
            ihdr = chunk_data
        elif chunk_type == b"IDAT":
            idat.extend(chunk_data)
        elif chunk_type == b"IEND":
            break

    if ihdr is None:
        raise ValueError(f"{path} is missing an IHDR chunk")

    width, height, bit_depth, color_type, _, _, interlace = struct.unpack(">IIBBBBB", ihdr)
    if color_type != 6 or bit_depth not in (8, 16) or interlace != 0:
        raise ValueError(
            f"{path} must be a non-interlaced RGBA PNG with 8-bit or 16-bit channels"
        )

    channels = 4
    bytes_per_sample = bit_depth // 8
    bytes_per_pixel = channels * bytes_per_sample
    stride = width * bytes_per_pixel
    inflated = zlib.decompress(bytes(idat))

    decoded = bytearray(height * stride)
    idx = 0
    previous = bytearray(stride)
    for y in range(height):
        filter_type = inflated[idx]
        idx += 1
        scanline = bytearray(inflated[idx : idx + stride])
        idx += stride
        current = bytearray(stride)
        for x in range(stride):
            left = current[x - bytes_per_pixel] if x >= bytes_per_pixel else 0
            up = previous[x]
            up_left = previous[x - bytes_per_pixel] if x >= bytes_per_pixel else 0
            value = scanline[x]
            if filter_type == 0:
                current[x] = value
            elif filter_type == 1:
                current[x] = (value + left) & 0xFF
            elif filter_type == 2:
                current[x] = (value + up) & 0xFF
            elif filter_type == 3:
                current[x] = (value + ((left + up) // 2)) & 0xFF
            elif filter_type == 4:
                current[x] = (value + paeth(left, up, up_left)) & 0xFF
            else:
                raise ValueError(f"{path} uses unsupported PNG filter {filter_type}")
        decoded[y * stride : (y + 1) * stride] = current
        previous = current

    return width, height, bit_depth, decoded


def write_rgba_png(path: Path, width: int, height: int, rgba: bytes) -> None:
    scanlines = bytearray()
    stride = width * 4
    for y in range(height):
        scanlines.append(0)
        scanlines.extend(rgba[y * stride : (y + 1) * stride])

    data = b"\x89PNG\r\n\x1a\n"
    data += png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
    data += png_chunk(b"IDAT", zlib.compress(bytes(scanlines), 9))
    data += png_chunk(b"IEND", b"")
    path.write_bytes(data)


def parse_color(value: str) -> tuple[int, int, int]:
    value = value.removeprefix("#")
    if len(value) != 6:
        raise ValueError("foreground color must use RRGGBB or #RRGGBB format")
    return int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16)


def make_template_png(source: Path, output: Path, foreground: tuple[int, int, int]) -> bytes:
    width, height, bit_depth, pixels = read_rgba_png(source)
    bytes_per_sample = bit_depth // 8
    bytes_per_pixel = 4 * bytes_per_sample
    stride = width * bytes_per_pixel

    rgba = bytearray()
    for y in range(height):
        base = y * stride
        for x in range(width):
            pos = base + x * bytes_per_pixel
            if bit_depth == 16:
                red = pixels[pos]
                green = pixels[pos + 2]
                blue = pixels[pos + 4]
                alpha = pixels[pos + 6]
            else:
                red, green, blue, alpha = pixels[pos : pos + 4]

            if alpha == 0 or (red > 248 and green > 248 and blue > 248):
                coverage_alpha = 0
            else:
                estimates = []
                for channel, fg_channel in zip((red, green, blue), foreground):
                    denominator = 255 - fg_channel
                    if denominator:
                        estimates.append((255 - channel) / denominator)
                coverage = max(0.0, min(1.0, max(estimates) if estimates else 0.0))
                coverage_alpha = int(round(coverage * alpha))

            rgba.extend((0, 0, 0, coverage_alpha))

    write_rgba_png(output, width, height, bytes(rgba))
    return output.read_bytes()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--linux-png", type=Path, default=ASSETS_DIR / "icon.png")
    parser.add_argument("--windows-ico", type=Path, default=ASSETS_DIR / "iconwin.ico")
    parser.add_argument("--darwin-source", type=Path, default=ASSETS_DIR / "icon.png")
    parser.add_argument("--foreground", default="#3C8CEC")
    parser.add_argument("--skip-linux", action="store_true")
    parser.add_argument("--skip-windows", action="store_true")
    parser.add_argument("--skip-darwin", action="store_true")
    args = parser.parse_args()

    if not args.skip_linux:
        write_go_array(ICON_DIR / "icon_linux.go", "linux", args.linux_png.read_bytes(), args.linux_png.name)

    if not args.skip_windows:
        write_go_array(
            ICON_DIR / "icon_windows.go",
            "windows",
            args.windows_ico.read_bytes(),
            args.windows_ico.name,
        )

    if not args.skip_darwin:
        with tempfile.TemporaryDirectory() as temp_dir:
            darwin_png = Path(temp_dir) / "icon_darwin.png"
            darwin_data = make_template_png(args.darwin_source, darwin_png, parse_color(args.foreground))
        write_go_array(
            ICON_DIR / "icon_darwin.go",
            "darwin",
            darwin_data,
            f"darwin template derived from {args.darwin_source.name}",
        )


if __name__ == "__main__":
    main()
